### ISSUE TITLE
Autowiring compatibility

### ISSUE THREAD

**Issue by CedCannes** [M6Web/AmqpBundle#53]
Would it be possible to make the services (producer, consumers) compatibles with autowiring ?

I would like to use them in a symfony 3.4 Command Class and I receive deprecated messages

`User Deprecated: The "m6_web_amqp.producer.my_topic" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

**Comment by Tobion** [comment]
All the consumers and producers have are of the same class. So it cannot use class based autowiring. What could be possible is to use named autowiring. But the deprecation you mention is not related to autowiring. You can always use explicit DI.

**Comment by Oliboy50** [comment]
@Tobion you're right 

the main issue is that our documentation is talking about getting the service directly from the container 😥 

```php
$msg = ["key" => "value"];
$this->get('m6_web_amqp.producer.myproducer')->publishMessage(serialize($msg));
```

**Comment by Tobion** [comment]
I see. Just rewrite that part and say the service id is `m6_web_amqp.producer.myproducer` (depending on your producer name).
